version: "2.4"
services: 
    sonarqube:
        restart: always
        image: docker.io/owasp/sonarqube:latest
        volumes:
          - /opt/sonarqube/data:/opt/sonarqube/data
        ports:
          - "9000:9000"
        healthcheck:
          test: ["CMD-SHELL","curl --silent --fail localhost:9000 || exit 1" ]
          interval: 30s
          timeout: 10s
          retries: 3

