version: "2.4"
services: 
    nexus:
        restart: always
        image: docker.io/sonatype/nexus3:latest
        volumes:
          - /opt/nexus3:/nexus-data
        ports:
          - "8081:8081"
        healthcheck:
          test: ["CMD-SHELL","curl --silent --fail localhost:8081 || exit 1" ]
          interval: 30s
          timeout: 10s
          retries: 3

